{{- if eq .Values.encryptedCredentials "" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.secret.name }}"
spec:
  secretStoreRef:
    name: aws-secret-manager-secretstore
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.secret.name }}"
  data:
    - secretKey: ENCRYPTED_CREDENTIALS
      remoteRef:
        key: "{{ .Values.secret.key }}"
        property: encryptedCredentials
{{- end }}
